# Generated by Django 5.2.7 on 2025-11-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0003_auto_rotation_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceaccount',
            options={'ordering': ('name',), 'permissions': (('manage_tokens', 'Can manage service account tokens and audit records'),), 'verbose_name': 'Service Account', 'verbose_name_plural': 'Service Accounts'},
        ),
        migrations.AlterModelOptions(
            name='serviceaccountauditlog',
            options={'default_permissions': ('view',), 'ordering': ('-created_at',), 'verbose_name': 'Service Account Audit Log', 'verbose_name_plural': 'Service Account Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='serviceaccounttoken',
            options={'default_permissions': ('view',), 'ordering': ('-created_at',), 'verbose_name': 'Service Account Token', 'verbose_name_plural': 'Service Account Tokens'},
        ),
    ]
