# Generated by Django 5.2.7 on 2026-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_accounts", "0004_alter_serviceaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccounttoken",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Última autenticação bem-sucedida com este token (EV-0023).",
                null=True,
            ),
        ),
    ]
