# Generated by Django 5.2.7 on 2025-10-09 10:53
# MODIFIED: This migration is now a no-op because models were moved
# to inventory app. Tables are managed by inventory migrations.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Depend on inventory creating tables first
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - tables are created by inventory app
        # This migration exists only to satisfy Django's migration system
    ]
