# Generated by Django 5.2.7 on 2025-10-09 23:48
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0001_initial'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - Port model is now in inventory app
    ]
