# Generated by Django 5.2.7 on 2025-10-13 11:32
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0002_port_zabbix_itemid'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - Device model is now in inventory app
    ]
