# Generated by Django 5.2.7 on 2025-10-13 19:46
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0006_alter_device_device_icon'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - Port and Device models are now in inventory app
    ]
