# Generated by Django 5.2.7 on 2025-10-14 22:20
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0007_port_zabbix_item_id_trafego_in_and_more'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - Device model is now in inventory app
    ]
