# Generated by Django 5.2.7 on 2025-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0008_device_cpu_usage_item_key_device_uptime_item_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_usage_item_key',
            field=models.CharField(blank=True, help_text='Zabbix item key for CPU usage (e.g. system.cpu.util[,user])', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='uptime_item_key',
            field=models.CharField(blank=True, help_text='Zabbix item key for uptime (e.g. system.uptime)', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='zabbix_hostid',
            field=models.CharField(blank=True, help_text='hostid inside Zabbix', max_length=32),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='path_coordinates',
            field=models.JSONField(blank=True, help_text="Coordinate list [{'lat': -16.6, 'lng': -49.2}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='status',
            field=models.CharField(choices=[('up', 'Operational'), ('down', 'Unavailable'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], default='unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='port',
            name='rx_power_item_key',
            field=models.CharField(blank=True, help_text='Optical RX power item key (e.g. hwEntityOpticalLaneRxPower[ID])', max_length=255),
        ),
        migrations.AlterField(
            model_name='port',
            name='tx_power_item_key',
            field=models.CharField(blank=True, help_text='Optical TX power item key (e.g. hwEntityOpticalLaneTxPower[ID])', max_length=255),
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_interfaceid',
            field=models.CharField(blank=True, help_text='interfaceid inside Zabbix', max_length=32),
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_item_id_trafego_in',
            field=models.CharField(blank=True, help_text='Zabbix itemid for ingress traffic', max_length=32),
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_item_id_trafego_out',
            field=models.CharField(blank=True, help_text='Zabbix itemid for egress traffic', max_length=32),
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_item_key',
            field=models.CharField(blank=True, help_text='Zabbix interface item key (e.g. net.if.in[ether10])', max_length=255),
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_itemid',
            field=models.CharField(blank=True, help_text='Generic itemid inside Zabbix', max_length=32),
        ),
    ]
