# Generated by Django 5.2.7 on 2025-10-25 21:59
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0008_device_cpu_usage_item_key_device_uptime_item_key'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - models are now in inventory app
    ]
