# Generated by Django 5.2.7 on 2025-10-26 03:12
# MODIFIED: No-op migration - models moved to inventory app

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0009_alter_device_cpu_usage_item_key_and_more'),
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        # No operations - models are now in inventory app
    ]
