# Generated by Django 5.2.7 on 2025-10-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0009_alter_device_cpu_usage_item_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False, 'ordering': ['site__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='fibercable',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fiberevent',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'managed': False, 'ordering': ['device__site__name', 'device__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
