# Generated by Django 5.2.7 on 2025-10-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0010_unmanage_inventory_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='zabbix_api_device',
        ),
        migrations.AlterModelTable(
            name='fibercable',
            table='zabbix_api_fibercable',
        ),
        migrations.AlterModelTable(
            name='fiberevent',
            table='zabbix_api_fiberevent',
        ),
        migrations.AlterModelTable(
            name='port',
            table='zabbix_api_port',
        ),
        migrations.AlterModelTable(
            name='site',
            table='zabbix_api_site',
        ),
    ]
