from __future__ import annotations

from django.urls import path

from inventory.api import devices as device_api
from inventory.api import fibers as fiber_api
from inventory.api import routes as routes_api
from inventory.api import zabbix_lookup as zabbix_lookup_api

app_name = "inventory-api"

urlpatterns = [
    path(
        "devices/<int:device_id>/ports/",
        device_api.api_device_ports,
        name="device-ports",
    ),
    path(
        "devices/<int:device_id>/ports/optical/",
        device_api.api_device_ports_with_optical,
        name="device-ports-optical",
    ),
    path(
        "ports/<int:port_id>/optical/",
        device_api.api_device_port_optical_status,
        name="port-optical-status",
    ),
    path(
        "ports/<int:port_id>/traffic/",
        device_api.api_port_traffic_history,
        name="port-traffic-history",
    ),
    path(
        "devices/add-from-zabbix/",
        device_api.api_add_device_from_zabbix,
        name="add-device-from-zabbix",
    ),
    path(
        "zabbix/discover-hosts/",
        device_api.api_zabbix_discover_hosts,
        name="zabbix-discover-hosts",
    ),
    path(
        "zabbix/lookup/hosts/",
        zabbix_lookup_api.lookup_hosts,
        name="zabbix-lookup-hosts",
    ),
    path(
        "zabbix/lookup/host-groups/",
        zabbix_lookup_api.lookup_host_groups,
        name="zabbix-lookup-host-groups",
    ),
    path(
        "zabbix/lookup/hosts/<str:hostid>/status/",
        zabbix_lookup_api.lookup_host_status,
        name="zabbix-lookup-host-status",
    ),
    path(
        "zabbix/lookup/hosts/<str:hostid>/interfaces/",
        zabbix_lookup_api.lookup_host_interfaces,
        name="zabbix-lookup-host-interfaces",
    ),
    path(
        "bulk/",
        device_api.api_bulk_create_inventory,
        name="bulk-create-inventory",
    ),
    path("sites/", device_api.api_sites, name="sites"),
    path(
        "fibers/<int:cable_id>/oper-status/",
        device_api.api_update_cable_oper_status,
        name="fiber-oper-status",
    ),
    path(
        "fibers/<int:cable_id>/cached-status/",
        fiber_api.api_fiber_cached_optical_status,
        name="fiber-cached-optical-status",
    ),
    path(
        "fibers/<int:cable_id>/cached-live-status/",
        fiber_api.api_fiber_cached_live_status,
        name="fiber-cached-live-status",
    ),
    path(
        "fibers/oper-status/",
        fiber_api.api_fibers_oper_status,
        name="fibers-oper-status",
    ),
    path("fibers/", fiber_api.api_fiber_cables, name="fibers"),
    path(
        "fibers/<int:cable_id>/",
        fiber_api.api_fiber_detail,
        name="fiber-detail",
    ),
    path(
        "fibers/<int:cable_id>/live-status/",
        fiber_api.api_fiber_live_status,
        name="fiber-live-status",
    ),
    path(
        "fibers/live-status/",
        fiber_api.api_fibers_live_status_all,
        name="fibers-live-status-all",
    ),
    path(
        "fibers/refresh-status/",
        fiber_api.api_fibers_refresh_status,
        name="fibers-refresh-status",
    ),
    path(
        "fibers/<int:cable_id>/value-mapping/",
        fiber_api.api_cable_value_mapping_status,
        name="fiber-value-mapping-status",
    ),
    path(
        "fibers/import-kml/",
        fiber_api.api_import_fiber_kml,
        name="fibers-import-kml",
    ),
    path(
        "fibers/manual-create/",
        fiber_api.api_create_manual_fiber,
        name="fibers-manual-create",
    ),
    path(
        "fibers/import-kml/modal/",
        fiber_api.import_kml_modal,
        name="fibers-import-kml-modal",
    ),
    path(
        "diagnostics/telnet/",
        device_api.api_test_telnet,
        name="diagnostics-telnet",
    ),
    path(
        "diagnostics/ping/",
        device_api.api_test_ping,
        name="diagnostics-ping",
    ),
    path(
        "diagnostics/ping-telnet/",
        device_api.api_test_ping_telnet,
        name="diagnostics-ping-telnet",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/up/",
        device_api.api_test_set_cable_up,
        name="diagnostics-cable-up",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/down/",
        device_api.api_test_set_cable_down,
        name="diagnostics-cable-down",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/unknown/",
        device_api.api_test_set_cable_unknown,
        name="diagnostics-cable-unknown",
    ),
    path(
        "routes/tasks/build/",
        routes_api.enqueue_build_route,
        name="routes-build",
    ),
    path(
        "routes/tasks/batch/",
        routes_api.enqueue_build_routes_batch,
        name="routes-build-batch",
    ),
    path(
        "routes/tasks/import/",
        routes_api.enqueue_import_route,
        name="routes-import",
    ),
    path(
        "routes/tasks/invalidate/",
        routes_api.enqueue_invalidate_route_cache,
        name="routes-invalidate-cache",
    ),
    path(
        "routes/tasks/health/",
        routes_api.enqueue_health_check,
        name="routes-health-check",
    ),
    path(
        "routes/tasks/status/<str:task_id_value>/",
        routes_api.task_status,
        name="routes-task-status",
    ),
    path(
        "routes/tasks/bulk/",
        routes_api.enqueue_bulk_operations,
        name="routes-bulk",
    ),
]
