from __future__ import annotations

from django.urls import path
from .api.splice_matrix import (
    SpliceBoxMatrixView,
    CreateFusionView,
    DeleteFusionView,
    BoxContextView,
)
from .api.cable_attachment import CableAttachmentViewSet
from .api.cable_split import CableSplitViewSet

from inventory.api import devices as device_api
from inventory.api import fibers as fiber_api
from inventory.api import routes as routes_api
from inventory.api import spatial as spatial_api
from inventory.api import zabbix_lookup as zabbix_lookup_api
from inventory.api.trace_route import trace_fiber_route
from inventory.api.infrastructure import (
    api_create_infrastructure,
    api_update_infrastructure,
    api_delete_infrastructure,
)

app_name = "inventory-api"

urlpatterns = [
    # Cable Attachments
    path(
        "cable-attachments/attach/",
        CableAttachmentViewSet.as_view({'post': 'attach'}),
        name="cable-attach",
    ),
    path(
        "cable-attachments/detach/",
        CableAttachmentViewSet.as_view({'post': 'detach'}),
        name="cable-detach",
    ),
    
    # Cable Split
    path(
        "cables/split-at-ceo/",
        CableSplitViewSet.as_view({'post': 'split_at_ceo'}),
        name="cable-split-ceo",
    ),
    
    path(
        "devices/select-options/",
        device_api.api_device_select_options,
        name="device-select-options",
    ),
    path(
        "devices/<int:device_id>/ports/",
        device_api.api_device_ports,
        name="device-ports",
    ),
    path(
        "devices/<int:device_id>/ports/live/",
        device_api.api_device_ports_live,
        name="device-ports-live",
    ),
    path(
        "devices/<int:device_id>/ports/optical/",
        device_api.api_device_ports_with_optical,
        name="device-ports-optical",
    ),
    path(
        "ports/<int:port_id>/optical/",
        device_api.api_device_port_optical_status,
        name="port-optical-status",
    ),
    path(
        "ports/<int:port_id>/traffic/",
        device_api.api_port_traffic_history,
        name="port-traffic-history",
    ),
    path(
        "devices/add-from-zabbix/",
        device_api.api_add_device_from_zabbix,
        name="add-device-from-zabbix",
    ),
    path(
        "zabbix/discover-hosts/",
        device_api.api_zabbix_discover_hosts,
        name="zabbix-discover-hosts",
    ),
    path(
        "zabbix/lookup/hosts/",
        zabbix_lookup_api.lookup_hosts,
        name="zabbix-lookup-hosts",
    ),
    path(
        "zabbix/lookup/hosts/grouped/",
        zabbix_lookup_api.lookup_hosts_grouped,
        name="zabbix-lookup-hosts-grouped",
    ),
    path(
        "zabbix/lookup/server-info/",
        zabbix_lookup_api.lookup_zabbix_server_info,
        name="zabbix-server-info",
    ),
    path(
        "zabbix/lookup/host-groups/",
        zabbix_lookup_api.lookup_host_groups,
        name="zabbix-lookup-host-groups",
    ),
    path(
        "zabbix/lookup/hosts/<str:hostid>/status/",
        zabbix_lookup_api.lookup_host_status,
        name="zabbix-lookup-host-status",
    ),
    path(
        "zabbix/lookup/hosts/<str:hostid>/interfaces/",
        zabbix_lookup_api.lookup_host_interfaces,
        name="zabbix-lookup-host-interfaces",
    ),
    path(
        "bulk/",
        device_api.api_bulk_create_inventory,
        name="bulk-create-inventory",
    ),
    path("sites/", device_api.api_sites, name="sites"),
    path(
        "fibers/<int:cable_id>/oper-status/",
        device_api.api_update_cable_oper_status,
        name="fiber-oper-status",
    ),
    path(
        "fibers/<int:cable_id>/cached-status/",
        fiber_api.api_fiber_cached_optical_status,
        name="fiber-cached-optical-status",
    ),
    path(
        "fibers/<int:cable_id>/cached-live-status/",
        fiber_api.api_fiber_cached_live_status,
        name="fiber-cached-live-status",
    ),
    path(
        "fibers/oper-status/",
        fiber_api.api_fibers_oper_status,
        name="fibers-oper-status",
    ),
    path("fibers/", fiber_api.api_fiber_cables, name="fibers"),
    path(
        "fibers/<int:cable_id>/",
        fiber_api.api_fiber_detail,
        name="fiber-detail",
    ),
    path(
        "fibers/<int:cable_id>/force-delete/",
        fiber_api.api_force_delete_fiber,
        name="fiber-force-delete",
    ),
    path(
        "fibers/<int:cable_id>/live-status/",
        fiber_api.api_fiber_live_status,
        name="fiber-live-status",
    ),
    path(
        "fibers/live-status/",
        fiber_api.api_fibers_live_status_all,
        name="fibers-live-status-all",
    ),
    path(
        "fibers/refresh-status/",
        fiber_api.api_fibers_refresh_status,
        name="fibers-refresh-status",
    ),
    path(
        "fibers/<int:cable_id>/value-mapping/",
        fiber_api.api_cable_value_mapping_status,
        name="fiber-value-mapping-status",
    ),
    path(
        "fibers/import-kml/",
        fiber_api.api_import_fiber_kml,
        name="fibers-import-kml",
    ),
    path(
        "fibers/manual-create/",
        fiber_api.api_create_manual_fiber,
        name="fibers-manual-create",
    ),
    path(
        "fibers/delete-bulk/",
        fiber_api.api_delete_fibers_bulk,
        name="fibers-delete-bulk",
    ),
    path(
        "fibers/import-kml/modal/",
        fiber_api.import_kml_modal,
        name="fibers-import-kml-modal",
    ),
    path(
        "diagnostics/telnet/",
        device_api.api_test_telnet,
        name="diagnostics-telnet",
    ),
    path(
        "diagnostics/ping/",
        device_api.api_test_ping,
        name="diagnostics-ping",
    ),
    path(
        "diagnostics/ping-telnet/",
        device_api.api_test_ping_telnet,
        name="diagnostics-ping-telnet",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/up/",
        device_api.api_test_set_cable_up,
        name="diagnostics-cable-up",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/down/",
        device_api.api_test_set_cable_down,
        name="diagnostics-cable-down",
    ),
    path(
        "diagnostics/cables/<int:cable_id>/unknown/",
        device_api.api_test_set_cable_unknown,
        name="diagnostics-cable-unknown",
    ),
    path(
        "routes/tasks/build/",
        routes_api.enqueue_build_route,
        name="routes-build",
    ),
    path(
        "routes/tasks/batch/",
        routes_api.enqueue_build_routes_batch,
        name="routes-build-batch",
    ),
    path(
        "routes/tasks/import/",
        routes_api.enqueue_import_route,
        name="routes-import",
    ),
    path(
        "routes/tasks/invalidate/",
        routes_api.enqueue_invalidate_route_cache,
        name="routes-invalidate-cache",
    ),
    path(
        "routes/tasks/health/",
        routes_api.enqueue_health_check,
        name="routes-health-check",
    ),
    path(
        "routes/tasks/status/<str:task_id_value>/",
        routes_api.task_status,
        name="routes-task-status",
    ),
    path(
        "routes/tasks/bulk/",
        routes_api.enqueue_bulk_operations,
        name="routes-bulk",
    ),
    # Spatial queries (Phase 10 - PostGIS)
    path(
        "segments/",
        spatial_api.api_route_segments_bbox,
        name="segments-bbox",
    ),
    path(
        "fibers/bbox/",
        spatial_api.api_fiber_cables_bbox,
        name="fibers-bbox",
    ),
    # Phase 7 - Spatial radius search with ST_DWithin
    path(
        "sites/radius/",
        spatial_api.api_sites_within_radius,
        name="sites-radius",
    ),
    # Phase 11 - Device Import System (Nov 2025)
    path(
        "devices/grouped/",
        device_api.api_inventory_grouped,
        name="inventory-grouped",
    ),
    path(
        "devices/zabbix-status/",
        device_api.api_devices_zabbix_status,
        name="devices-zabbix-status",
    ),
    path(
        "devices/import-batch/",
        device_api.api_import_batch,
        name="inventory-import-batch",
    ),
    path(
        "devices/<int:device_id>/",
        device_api.api_device_delete,
        name="device-delete",
    ),
    path(
        "infrastructure/",
        api_create_infrastructure,
        name="infrastructure-create",
    ),
    path(
        "infrastructure/<int:pk>/",
        api_update_infrastructure,
        name="infrastructure-update",
    ),
    path(
        "infrastructure/<int:pk>/delete/",
        api_delete_infrastructure,
        name="infrastructure-delete",
    ),
    path(
        'splice-boxes/<int:id>/matrix/',
        SpliceBoxMatrixView.as_view(),
        name='splice-box-matrix',
    ),
    path(
        'splice-boxes/<int:id>/context/',
        BoxContextView.as_view(),
        name='splice-box-context',
    ),
    path(
        'fusions/',
        CreateFusionView.as_view(),
        name='create-fusion',
    ),
    path(
        'fusions/<int:fiber_id>/',
        DeleteFusionView.as_view(),
        name='delete-fusion',
    ),
    # Trace Route - Optical path tracing (Phase 11.5)
    path(
        'trace-route/',
        trace_fiber_route,
        name='trace-route',
    ),
]
