# Generated by Django 5.2.7 on 2025-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial_from_existing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='zabbix_item_id_trafego_in',
            field=models.CharField(blank=True, db_column='zabbix_item_id_trafego_in', help_text='Zabbix itemid for ingress traffic', max_length=32),
        ),
        migrations.RenameField(
            model_name='port',
            old_name='zabbix_item_id_trafego_in',
            new_name='zabbix_item_id_traffic_in',
        ),
        migrations.AlterField(
            model_name='port',
            name='zabbix_item_id_trafego_out',
            field=models.CharField(blank=True, db_column='zabbix_item_id_trafego_out', help_text='Zabbix itemid for egress traffic', max_length=32),
        ),
        migrations.RenameField(
            model_name='port',
            old_name='zabbix_item_id_trafego_out',
            new_name='zabbix_item_id_traffic_out',
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='path_coordinates',
            field=models.JSONField(blank=True, help_text="Coordinate list e.g. [{'lat': -16.6, 'lng': -49.2}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='rx_power_item_key',
            field=models.CharField(blank=True, help_text='Optical RX power (e.g. hwEntityOpticalLaneRxPower[ID])', max_length=255),
        ),
        migrations.AlterField(
            model_name='port',
            name='tx_power_item_key',
            field=models.CharField(blank=True, help_text='Optical TX power (e.g. hwEntityOpticalLaneTxPower[ID])', max_length=255),
        ),
    ]
