# Generated by Django 5.2.7 on 2025-11-09 16:26

from typing import Any, cast

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils.text import slugify


def populate_site_slugs(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    Site = cast(Any, apps.get_model("inventory", "Site"))

    for site in Site.objects.all().order_by("pk"):
        base_value = (
            getattr(site, "display_name", None)
            or getattr(site, "city", None)
            or getattr(site, "address_line1", None)
        )
        base = slugify(base_value or "") or f"site-{site.pk}"
        candidate = base[:160]
        suffix = 2
        while (
            Site.objects.exclude(pk=site.pk)
            .filter(slug=candidate)
            .exists()
        ):
            suffix_str = f"-{suffix}"
            candidate = f"{base[:160 - len(suffix_str)]}{suffix_str}"
            suffix += 1
        site.slug = candidate
        site.save(update_fields=["slug"])


def normalize_blank_fields(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    Site = cast(Any, apps.get_model("inventory", "Site"))
    Site.objects.filter(address_line1__isnull=True).update(address_line1="")
    Site.objects.filter(address_line2__isnull=True).update(address_line2="")
    Site.objects.filter(address_line3__isnull=True).update(address_line3="")
    Site.objects.filter(state__isnull=True).update(state="")
    Site.objects.filter(postal_code__isnull=True).update(postal_code="")
    Site.objects.filter(country__isnull=True).update(country="")
    Site.objects.filter(rack_location__isnull=True).update(rack_location="")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_route_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="name",
            new_name="display_name",
        ),
        migrations.AlterField(
            model_name="site",
            name="display_name",
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="city",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="site",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="address_line3",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="state",
            field=models.CharField(blank=True, default="", max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="country",
            field=models.CharField(blank=True, default="", max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="rack_location",
            field=models.CharField(blank=True, default="", max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                editable=False,
                max_length=160,
            ),
        ),
        migrations.RunPython(populate_site_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(
                editable=False,
                max_length=160,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="address_line3",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="state",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="site",
            name="postal_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="site",
            name="country",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="site",
            name="rack_location",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.RunPython(
            normalize_blank_fields,
            migrations.RunPython.noop,
        ),
    ]
