# Generated by Django 5.2.7 on 2025-11-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_site_schema_normalization'),
    ]

    operations = []
