# Generated by Django 5.2.7 on 2025-11-09 16:30

from django.apps.registry import Apps
from django.db import connection, migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def ensure_route_tables(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """Create inventory_route* tables if the legacy ones are missing."""

    with connection.cursor() as cursor:
        if connection.vendor != "sqlite":
            return

        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )
        tables = {row[0] for row in cursor.fetchall()}

        required_tables = {
            "inventory_route",
            "inventory_routesegment",
            "inventory_routeevent",
        }
        if required_tables.issubset(tables):
            return

        legacy_tables = {
            "routes_builder_route": "inventory_route",
            "routes_builder_routesegment": "inventory_routesegment",
            "routes_builder_routeevent": "inventory_routeevent",
        }

        for old_name, new_name in legacy_tables.items():
            if old_name in tables and new_name not in tables:
                cursor.execute(
                    f"ALTER TABLE {old_name} RENAME TO {new_name}"
                )

        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        )
        tables = {row[0] for row in cursor.fetchall()}

        # Recreate tables when neither legacy nor target tables exist.
        create_statements = {
            "inventory_route": (
                "CREATE TABLE IF NOT EXISTS inventory_route ("
                "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "name VARCHAR(150) UNIQUE NOT NULL,"
                "description TEXT NOT NULL DEFAULT '',"
                "origin_port_id INTEGER NOT NULL,"
                "destination_port_id INTEGER NOT NULL,"
                "status VARCHAR(20) NOT NULL DEFAULT 'planned',"
                "length_km NUMERIC(7,3),"
                "estimated_loss_db NUMERIC(5,2),"
                "measured_loss_db NUMERIC(5,2),"
                "last_built_at DATETIME,"
                "last_built_by VARCHAR(150) NOT NULL DEFAULT '',"
                "import_source VARCHAR(150) NOT NULL DEFAULT '',"
                "metadata JSON,"
                "created_at DATETIME NOT NULL,"
                "updated_at DATETIME NOT NULL,"
                "FOREIGN KEY(origin_port_id) REFERENCES inventory_port(id)"
                " ON DELETE PROTECT,"
                "FOREIGN KEY(destination_port_id) REFERENCES "
                "inventory_port(id) ON DELETE PROTECT"
                ")"
            ),
            "inventory_routesegment": (
                "CREATE TABLE IF NOT EXISTS inventory_routesegment ("
                "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "route_id INTEGER NOT NULL REFERENCES inventory_route(id)"
                " ON DELETE CASCADE,"
                "sequence INTEGER NOT NULL,"
                "port_a_id INTEGER NOT NULL REFERENCES inventory_port(id)"
                " ON DELETE PROTECT,"
                "port_b_id INTEGER NOT NULL REFERENCES inventory_port(id)"
                " ON DELETE PROTECT,"
                "length_km NUMERIC(7,3),"
                "metadata JSON"
                ")"
            ),
            "inventory_routeevent": (
                "CREATE TABLE IF NOT EXISTS inventory_routeevent ("
                "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "route_id INTEGER NOT NULL REFERENCES inventory_route(id)"
                " ON DELETE CASCADE,"
                "timestamp DATETIME NOT NULL,"
                "previous_status VARCHAR(20) NOT NULL DEFAULT '',"
                "new_status VARCHAR(20) NOT NULL,"
                "message TEXT NOT NULL DEFAULT ''"
                ")"
            ),
        }

        for table_name in required_tables:
            if table_name not in tables:
                cursor.execute(create_statements[table_name])


def reverse_route_tables(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    # No-op reverse; tables already renamed or created.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_device_options_alter_port_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            ensure_route_tables,
            reverse_route_tables,
        ),
    ]
