# Generated by Django 5.2.7 on 2025-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_routes_table_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['site__display_name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['device__site__display_name', 'device__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['display_name']},
        ),
        migrations.AddField(
            model_name='port',
            name='last_optical_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp da última coleta óptica assíncrona', null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='last_rx_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último valor RX dBm coletado do Zabbix (cache assíncrono)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='last_tx_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Último valor TX dBm coletado do Zabbix (cache assíncrono)', max_digits=5, null=True),
        ),
    ]
