# Generated by Django 5.2.7 on 2025-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_device_options_alter_port_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercable',
            name='last_live_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp do último cálculo de status live', null=True),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='last_live_status',
            field=models.CharField(blank=True, help_text="Último status 'live' calculado (agregação de fontes)", max_length=20),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='last_status_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp da última verificação de status operacional', null=True),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='last_status_dest',
            field=models.CharField(blank=True, help_text='Último status operacional da porta de destino (cache)', max_length=20),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='last_status_origin',
            field=models.CharField(blank=True, help_text='Último status operacional da porta de origem (cache)', max_length=20),
        ),
    ]
