# Generated by Django 5.2.7 on 2025-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_lenient_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='primary_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Primary IP address of the device', null=True),
        ),
    ]
