# Generated by Django 5.2.7 on 2025-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_device_primary_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_groupid', models.CharField(help_text='groupid inside Zabbix', max_length=32, unique=True)),
                ('name', models.CharField(help_text="Group name from Zabbix (e.g. 'Switch Huawei')", max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_device_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Zabbix host groups for this device', related_name='devices', to='inventory.devicegroup'),
        ),
    ]
