# Generated by Django 5.2.7 on 2025-11-18 23:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_devicegroup_device_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
