# Generated by Django 5.2.7 on 2025-11-18 23:22

from django.db import migrations

from inventory.migration_utils.gis import build_point


def populate_site_locations(apps, schema_editor):
    """
    Populate Site.location PointField from existing latitude/longitude.
    
    This data migration converts DecimalField coordinates to PostGIS Point
    geometry. Uses ST_MakePoint equivalent via Django GIS
    Point(longitude, latitude, srid=4326).
    
    Note: Coordinate order is (longitude, latitude) for GIS, not (lat, lng).
    """
    Site = apps.get_model('inventory', 'Site')
    
    # Get all sites with both lat/lng coordinates
    sites_with_coords = Site.objects.filter(
        latitude__isnull=False,
        longitude__isnull=False
    )
    
    updated_count = 0
    
    for site in sites_with_coords:
        # Create Point geometry (longitude, latitude order!)
        site.location = build_point(
            float(site.longitude),
            float(site.latitude),
            srid=4326,
        )
        # Use update_fields for efficiency (only updates location column)
        site.save(update_fields=['location'])
        updated_count += 1
    
    print(f"[OK] Populated location for {updated_count} sites")


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: Clear location field.
    
    Note: This doesn't restore lat/lng (they were never deleted),
    it just clears the derived location PointField.
    """
    Site = apps.get_model('inventory', 'Site')
    Site.objects.update(location=None)
    print("[OK] Cleared location field for all sites")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_add_site_location'),
    ]

    operations = [
        migrations.RunPython(
            populate_site_locations,
            reverse_code=reverse_populate
        ),
    ]
