# Generated by Django 5.2.7 on 2025-11-18 23:23

from django.db import migrations


def create_site_location_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS idx_site_location '
        'ON zabbix_api_site USING GIST (location);'
    )


def drop_site_location_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute('DROP INDEX IF EXISTS idx_site_location;')


class Migration(migrations.Migration):
    """
    Create GIST index on Site.location for O(log n) spatial queries.
    
    This enables fast radius searches using ST_DWithin with PostGIS.
    Expected performance: ~5ms for 1000 sites (vs ~60ms without index).
    """

    dependencies = [
        ('inventory', '0017_populate_site_location'),
    ]

    operations = [
        migrations.RunPython(
            create_site_location_index,
            reverse_code=drop_site_location_index,
        ),
    ]
