# Generated by Django 5.2.7 on 2025-11-18 23:23

from django.db import migrations


class Migration(migrations.Migration):
    """
    Create GIST index on Site.location for O(log n) spatial queries.
    
    This enables fast radius searches using ST_DWithin with PostGIS.
    Expected performance: ~5ms for 1000 sites (vs ~60ms without index).
    """

    dependencies = [
        ('inventory', '0017_populate_site_location'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'CREATE INDEX idx_site_location '
                'ON zabbix_api_site USING GIST (location);'
            ),
            reverse_sql='DROP INDEX IF EXISTS idx_site_location;'
        ),
    ]
