# Generated by Django 5.2.7 on 2025-11-18 23:50

from django.db import migrations

from inventory.migration_utils.gis import get_point_field_class


PointField = get_point_field_class()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_site_location_gist_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='location',
            field=PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
