# Generated by Django 5.2.7 on 2025-11-18 23:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_site_location_gist_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
