# Generated by Django 5.2.7 on 2025-11-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_change_location_to_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('backbone', 'Backbone / IP'), ('gpon', 'GPON / FTTx'), ('dwdm', 'DWDM / Óptico'), ('access', 'Acesso / Clientes')], db_index=True, default='backbone', help_text='Define a camada lógica para visualização nos mapas', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='enable_email_alert',
            field=models.BooleanField(default=False, help_text='Enviar e-mail para equipe de NOC', verbose_name='Alerta E-mail'),
        ),
        migrations.AddField(
            model_name='device',
            name='enable_screen_alert',
            field=models.BooleanField(default=True, help_text='Exibir pop-up no dashboard em caso de falha', verbose_name='Alerta em Tela'),
        ),
        migrations.AddField(
            model_name='device',
            name='enable_whatsapp_alert',
            field=models.BooleanField(default=False, help_text='Enviar mensagem automática para o grupo de operações', verbose_name='Alerta WhatsApp'),
        ),
        migrations.AddField(
            model_name='device',
            name='monitoring_group',
            field=models.ForeignKey(blank=True, help_text='Grupo principal para organização visual no frontend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_devices', to='inventory.devicegroup'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category', 'monitoring_group'], name='device_cat_grp_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zabbix_hostid'], name='device_zabbix_idx'),
        ),
    ]
