# Generated by Django 5.2.7 on 2025-11-23 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_device_category_device_enable_email_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Regex pattern to match device name (case-insensitive)', max_length=255)),
                ('category', models.CharField(choices=[('backbone', 'Backbone / IP'), ('gpon', 'GPON / FTTx'), ('dwdm', 'DWDM / Óptico'), ('access', 'Acesso / Clientes')], help_text='Category to assign when pattern matches', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive rules are ignored during import')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Lower numbers = higher priority (0 = highest)')),
                ('description', models.CharField(blank=True, help_text='Human-readable explanation of the rule', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Optional monitoring group to auto-assign', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.devicegroup')),
            ],
            options={
                'db_table': 'inventory_import_rule',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='rule_active_prio_idx')],
            },
        ),
    ]
