# Generated by Django manually (Phase 11.5 - Physical Fiber Hierarchy)

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_default_profiles(apps, schema_editor):
    """
    Cria perfis padrão de cabos mais comuns no Brasil.
    """
    FiberProfile = apps.get_model('inventory', 'FiberProfile')
    
    default_profiles = [
        {
            'name': 'Drop Compacto 1FO',
            'total_fibers': 1,
            'tube_count': 1,
            'fibers_per_tube': 1,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Drop Flat 2FO',
            'total_fibers': 2,
            'tube_count': 1,
            'fibers_per_tube': 2,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 6FO (Tubo Único)',
            'total_fibers': 6,
            'tube_count': 1,
            'fibers_per_tube': 6,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 12FO (Tubo Único)',
            'total_fibers': 12,
            'tube_count': 1,
            'fibers_per_tube': 12,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 36FO (Multitubo)',
            'total_fibers': 36,
            'tube_count': 3,
            'fibers_per_tube': 12,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 48FO (Multitubo)',
            'total_fibers': 48,
            'tube_count': 4,
            'fibers_per_tube': 12,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 72FO (Multitubo)',
            'total_fibers': 72,
            'tube_count': 6,
            'fibers_per_tube': 12,
            'manufacturer': 'Genérico',
        },
        {
            'name': 'Cabo 144FO (Multitubo)',
            'total_fibers': 144,
            'tube_count': 12,
            'fibers_per_tube': 12,
            'manufacturer': 'Genérico',
        },
    ]
    
    for profile_data in default_profiles:
        FiberProfile.objects.get_or_create(
            name=profile_data['name'],
            defaults=profile_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_importrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: 'Cabo AS-80 48FO (4x12)', '144FO (12x12)'", max_length=100, unique=True)),
                ('total_fibers', models.IntegerField(help_text='Capacidade total de fibras no cabo')),
                ('tube_count', models.IntegerField(default=1, help_text='Quantidade de tubos loose que o cabo possui')),
                ('fibers_per_tube', models.IntegerField(default=12, help_text='Quantidade de fibras dentro de cada tubo')),
                ('manufacturer', models.CharField(blank=True, help_text='Fabricante do cabo (Furukawa, Prysmian, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Fibra',
                'verbose_name_plural': 'Perfis de Fibra',
                'db_table': 'inventory_fiber_profile',
                'ordering': ['total_fibers', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fibercable',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Perfil técnico que define a estrutura interna do cabo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables', to='inventory.fiberprofile'),
        ),
        migrations.CreateModel(
            name='BufferTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Número sequencial do tubo (1, 2, 3...)')),
                ('color', models.CharField(help_text='Nome da cor do tubo conforme padrão ABNT', max_length=30)),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='Código hexadecimal da cor', max_length=7)),
                ('cable', models.ForeignKey(help_text='Cabo ao qual este tubo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='tubes', to='inventory.fibercable')),
            ],
            options={
                'verbose_name': 'Tubo Loose',
                'verbose_name_plural': 'Tubos Loose',
                'db_table': 'inventory_buffer_tube',
                'ordering': ['cable', 'number'],
                'unique_together': {('cable', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FiberStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Número da fibra dentro do tubo (1-12 tipicamente)')),
                ('absolute_number', models.IntegerField(help_text='Número sequencial no cabo (1-144 para cabo 144FO)')),
                ('color', models.CharField(help_text='Nome da cor da fibra conforme padrão ABNT', max_length=30)),
                ('color_hex', models.CharField(help_text='Código hexadecimal da cor', max_length=7)),
                ('status', models.CharField(choices=[('dark', 'Apagada (Dark Fiber)'), ('lit', 'Iluminada (Ativa)'), ('reserved', 'Reservada'), ('broken', 'Rompida')], default='dark', help_text='Status operacional da fibra', max_length=20)),
                ('attenuation_db', models.DecimalField(blank=True, decimal_places=2, help_text='Atenuação medida em dB (OTDR)', max_digits=5, null=True)),
                ('last_test_date', models.DateTimeField(blank=True, help_text='Última medição OTDR', null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações técnicas sobre esta fibra')),
                ('connected_device_port', models.OneToOneField(blank=True, help_text='Porta de dispositivo conectada (DIO, ODF, Switch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_fiber', to='inventory.port')),
                ('fused_to', models.OneToOneField(blank=True, help_text='Fibra com a qual esta está fusionada (emenda)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusion_pair', to='inventory.fiberstrand')),
                ('tube', models.ForeignKey(help_text='Tubo ao qual esta fibra pertence', on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='inventory.buffertube')),
            ],
            options={
                'verbose_name': 'Filamento de Fibra',
                'verbose_name_plural': 'Filamentos de Fibra',
                'db_table': 'inventory_fiber_strand',
                'ordering': ['absolute_number'],
                'unique_together': {('tube', 'number')},
            },
        ),
        migrations.RunPython(create_default_profiles),
    ]
