# Generated by Django 5.2.7 on 2025-11-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_fiber_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercable',
            name='site_a',
            field=models.ForeignKey(blank=True, help_text='Site de origem (opcional até conexão lógica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables_start', to='inventory.site'),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='site_b',
            field=models.ForeignKey(blank=True, help_text='Site de destino (opcional até conexão lógica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cables_end', to='inventory.site'),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='destination_port',
            field=models.ForeignKey(blank=True, help_text='Porta de destino (opcional até terminação física)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiber_destination', to='inventory.port'),
        ),
        migrations.AlterField(
            model_name='fibercable',
            name='origin_port',
            field=models.ForeignKey(blank=True, help_text='Porta de origem (opcional até terminação física)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiber_origin', to='inventory.port'),
        ),
    ]
