# Generated by Django 5.2.7 on 2025-11-28 22:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_site_fields_to_cable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('slack', 'Reserva Técnica'), ('splice_box', 'Caixa de Emenda (CEO)'), ('splitter_box', 'Caixa de Atendimento (CTO)'), ('transition', 'Transição Aéreo/Subt')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Ex: CEO-01-BKB', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('distance_from_origin', models.FloatField(blank=True, help_text='Distância em metros a partir do início do cabo', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_points', to='inventory.fibercable')),
            ],
            options={
                'verbose_name': 'Ponto de Infraestrutura',
                'verbose_name_plural': 'Pontos de Infraestrutura',
                'db_table': 'inventory_fiber_infrastructure',
                'ordering': ['distance_from_origin', 'created_at', 'id'],
            },
        ),
    ]
