# Generated by Django 5.2.7 on 2025-11-29 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_fiberinfrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceBoxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(default='Fibracem', max_length=50)),
                ('model_code', models.CharField(blank=True, max_length=50)),
                ('max_trays', models.IntegerField(help_text='Máximo de bandejas suportadas')),
                ('splices_per_tray', models.IntegerField(default=24, help_text='Fusões por bandeja (padrão Fibracem SVT = 24)')),
                ('cable_ports_oval', models.IntegerField(default=1, help_text='Entrada oval (pass-through, 10–25mm)')),
                ('cable_ports_round', models.IntegerField(default=4, help_text='Entradas cilíndricas (derivação, 8–18mm)')),
                ('length_mm', models.IntegerField(default=492)),
                ('diameter_mm', models.IntegerField(default=195)),
            ],
            options={
                'db_table': 'inventory_splice_box_template',
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fiberinfrastructure',
            name='installed_trays',
            field=models.IntegerField(default=1, help_text='Quantidade de bandejas instaladas fisicamente'),
        ),
        migrations.AddField(
            model_name='fiberstrand',
            name='fusion_infrastructure',
            field=models.ForeignKey(blank=True, help_text='CEO onde ocorreu a fusão (para matriz visual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusions', to='inventory.fiberinfrastructure'),
        ),
        migrations.AddField(
            model_name='fiberstrand',
            name='fusion_slot',
            field=models.IntegerField(blank=True, help_text='Número do slot (1–24)', null=True),
        ),
        migrations.AddField(
            model_name='fiberstrand',
            name='fusion_tray',
            field=models.IntegerField(blank=True, help_text='Número da bandeja', null=True),
        ),
        migrations.AddField(
            model_name='fiberinfrastructure',
            name='box_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_boxes', to='inventory.spliceboxtemplate'),
        ),
        migrations.CreateModel(
            name='InfrastructureCableAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_type', models.CharField(choices=[('oval', 'Oval (Passagem)'), ('round', 'Redonda (Derivação)')], max_length=10)),
                ('is_pass_through', models.BooleanField(default=False, help_text='Se verdadeiro, cabo entra e sai (sangria/pass-through)')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.fibercable')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_cables', to='inventory.fiberinfrastructure')),
            ],
            options={
                'db_table': 'inventory_infrastructure_cable_attachment',
                'ordering': ['infrastructure_id'],
                'unique_together': {('infrastructure', 'cable', 'port_type')},
            },
        ),
    ]
