# Generated by Django 5.2.7 on 2025-12-08 23:59

import logging

import django.db.models.deletion
from django.db import migrations, models


logger = logging.getLogger(__name__)


def migrate_legacy_fusions(apps, schema_editor):
    FiberStrand = apps.get_model('inventory', 'FiberStrand')
    FiberFusion = apps.get_model('inventory', 'FiberFusion')

    slots_seen: set[tuple[int, int, int]] = set()
    skipped_missing_meta: list[int] = []
    skipped_duplicate_slot: list[int] = []

    strands = FiberStrand.objects.exclude(fusion_infrastructure__isnull=True)
    for strand in strands.iterator():
        infra_id = strand.fusion_infrastructure_id
        tray = strand.fusion_tray
        slot = strand.fusion_slot

        if infra_id is None or tray is None or slot is None:
            skipped_missing_meta.append(strand.pk)
            continue

        slot_key = (infra_id, tray, slot)
        if slot_key in slots_seen:
            skipped_duplicate_slot.append(strand.pk)
            continue

        partner_id = strand.fused_to_id or strand.pk

        FiberFusion.objects.create(
            infrastructure_id=infra_id,
            tray=tray,
            slot=slot,
            fiber_a_id=strand.pk,
            fiber_b_id=partner_id,
        )

        slots_seen.add(slot_key)

    if skipped_missing_meta:
        logger.warning(
            "FiberFusion migration ignorou %d fibras sem metadados: %s",
            len(skipped_missing_meta),
            skipped_missing_meta[:50],
        )

    if skipped_duplicate_slot:
        logger.warning(
            "FiberFusion migration pulou %d fibras com slot duplicado: %s",
            len(skipped_duplicate_slot),
            skipped_duplicate_slot[:50],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_cable_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberFusion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tray',
                    models.IntegerField(
                        blank=True,
                        help_text=(
                            'Número da bandeja onde a fusão está '
                            'registrada'
                        ),
                        null=True,
                    ),
                ),
                (
                    'slot',
                    models.IntegerField(
                        blank=True,
                        help_text='Slot físico dentro da bandeja (1–24)',
                        null=True,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'fiber_a',
                    models.ForeignKey(
                        help_text='Primeira fibra participante da fusão',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fusions_as_a',
                        to='inventory.fiberstrand',
                    ),
                ),
                (
                    'fiber_b',
                    models.ForeignKey(
                        help_text='Segunda fibra participante da fusão',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fusions_as_b',
                        to='inventory.fiberstrand',
                    ),
                ),
                (
                    'infrastructure',
                    models.ForeignKey(
                        help_text=(
                            'Infraestrutura (CEO) onde a fusão foi '
                            'realizada'
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fusions',
                        to='inventory.fiberinfrastructure',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Fusão de Fibra',
                'verbose_name_plural': 'Fusões de Fibra',
                'db_table': 'inventory_fiber_fusion',
                'indexes': [
                    models.Index(
                        fields=['fiber_a'],
                        name='idx_fusion_fiber_a',
                    ),
                    models.Index(
                        fields=['fiber_b'],
                        name='idx_fusion_fiber_b',
                    ),
                    models.Index(
                        fields=['infrastructure'],
                        name='idx_fusion_infrastructure',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('infrastructure', 'tray', 'slot'),
                        name='inventory_fiber_fusion_unique_slot',
                    ),
                ],
            },
        ),
        migrations.RenameIndex(
            model_name='cablesegment',
            new_name='idx_cable_seg_num',
            old_name='idx_cable_segment_num',
        ),
        migrations.RenameIndex(
            model_name='cablesegment',
            new_name='idx_seg_start',
            old_name='idx_segment_start',
        ),
        migrations.RenameIndex(
            model_name='cablesegment',
            new_name='idx_seg_end',
            old_name='idx_segment_end',
        ),
        migrations.RunPython(
            migrate_legacy_fusions,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='fiberstrand',
            name='fused_to',
        ),
        migrations.RemoveField(
            model_name='fiberstrand',
            name='fusion_infrastructure',
        ),
        migrations.RemoveField(
            model_name='fiberstrand',
            name='fusion_slot',
        ),
        migrations.RemoveField(
            model_name='fiberstrand',
            name='fusion_tray',
        ),
    ]
