# Generated by Django 5.2.7 on 2025-12-19 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_fiberfusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablesegment',
            name='end_infrastructure',
            field=models.ForeignKey(blank=True, help_text='Infraestrutura de destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_ending_here', to='inventory.fiberinfrastructure'),
        ),
        migrations.AlterField(
            model_name='cablesegment',
            name='start_infrastructure',
            field=models.ForeignKey(blank=True, help_text='Infraestrutura de origem (CEO, Site, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_starting_here', to='inventory.fiberinfrastructure'),
        ),
    ]
