# Generated by Django 5.2.7 on 2025-12-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_change_cablesegment_infrastructure_protect_to_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercable',
            name='parent_cable',
            field=models.ForeignKey(blank=True, help_text='Cabo pai se este for um segmento criado por split', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_segments', to='inventory.fibercable'),
        ),
    ]
