# Generated by Django 5.2.7 on 2026-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_add_parent_cable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesegment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('broken', 'Rompido'), ('inactive', 'Inativo')], default='active', help_text='Status físico do segmento (ativo, rompido, inativo)', max_length=20),
        ),
    ]
