# Generated by Django 5.2.7 on 2026-01-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_add_status_to_cablesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructurecableattachment',
            name='connected_segment',
            field=models.ForeignKey(blank=True, help_text='Segmento físico que está anexado (para cabos rompidos com pontas soltas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='inventory.cablesegment'),
        ),
        migrations.AddField(
            model_name='infrastructurecableattachment',
            name='is_start_of_segment',
            field=models.BooleanField(default=True, help_text='Se verdadeiro, é a ponta INÍCIO do segmento; se falso, é a ponta FIM'),
        ),
    ]
