# Generated by Django 5.2.7 on 2026-01-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_add_segment_attachment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberinfrastructure',
            name='cable',
            field=models.ForeignKey(blank=True, help_text='Cabo ao qual este ponto pertence (pode ser null para CEOs standalone)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_points', to='inventory.fibercable'),
        ),
    ]
