# Generated by Django 5.2.7 on 2026-01-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_allow_standalone_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesegment',
            name='has_loose_ends',
            field=models.BooleanField(default=False, help_text='Indica se o segmento tem pontas soltas (desconectadas) após rompimento'),
        ),
    ]
