# Generated by Django 5.2.7 on 2026-01-22 12:51

import inventory.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_add_has_loose_ends_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dashboard_config',
            field=inventory.fields.LenientJSONField(blank=True, default=dict, help_text='Configuração de widgets e layout da dashboard do equipamento. Exemplo: {"layout": "grid", "widgets": [{"type": "gauge", "metric": "cpu", "title": "CPU"}]}'),
        ),
    ]
