# Generated by Django 5.2.7 on 2026-01-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_add_memory_cpu_manual_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dashboard_config',
        ),
        migrations.AddField(
            model_name='port',
            name='alarm_critical_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limiar crítico (dBm) - dispara alarme quando RX ficar abaixo deste valor', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='alarm_enabled',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, alarmes serão disparados quando limiares forem ultrapassados'),
        ),
        migrations.AddField(
            model_name='port',
            name='alarm_notifications',
            field=models.JSONField(blank=True, default=dict, help_text='Configuração de canais de notificação (email, dashboard, whatsapp, telegram, webhook)', null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='alarm_warning_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limiar de atenção (dBm) - dispara alerta quando RX ficar abaixo deste valor', max_digits=5, null=True),
        ),
    ]
