# Generated by Django 5.2.7 on 2026-01-24 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_add_port_alarm_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalPowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento da medição')),
                ('rx_power', models.DecimalField(blank=True, decimal_places=2, help_text='Potência recebida (RX) em dBm no momento do snapshot', max_digits=5, null=True)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=2, help_text='Potência transmitida (TX) em dBm no momento do snapshot', max_digits=5, null=True)),
                ('port', models.ForeignKey(help_text='Porta à qual este snapshot pertence', on_delete=django.db.models.deletion.CASCADE, related_name='optical_history', to='inventory.port')),
            ],
            options={
                'verbose_name': 'Snapshot de Potência Óptica',
                'verbose_name_plural': 'Snapshots de Potência Óptica',
                'db_table': 'inventory_optical_power_snapshot',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['port', '-timestamp'], name='inventory_o_port_id_686660_idx')],
            },
        ),
    ]
