# Generated by Django 5.2.7 on 2026-01-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_opticalpowersnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpticalPowerSnapshot',
        ),
    ]
