# Generated by ChatGPT
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_remove_optical_snapshot_model"),
        ("setup_app", "0024_add_map_theme_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiberCableAlarmConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("department_group", "Department group"), ("system_user", "System user"), ("contact", "Contact")], max_length=32, help_text="Tipo de destino (grupo, usuário ou contato).")),
                ("target_snapshot", models.JSONField(blank=True, default=dict, help_text="Fotografia dos dados do destino (nome, resumo, etc.).")),
                ("channels", models.JSONField(blank=True, default=list, help_text="Lista de canais de notificação habilitados (email, whatsapp, sms, telegram).")),
                ("trigger_level", models.CharField(choices=[("warning", "Warning"), ("critical", "Critical")], default="warning", help_text="Nível que dispara o alarme (warning ou critical).", max_length=16)),
                ("persist_minutes", models.PositiveIntegerField(default=0, help_text="Minutos de persistência antes do disparo (0 para imediato).")),
                ("description", models.TextField(blank=True, help_text="Descrição opcional ou observações do alarme.")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Metadados adicionais (ex: IDs externos, preferências por canal).")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact", models.ForeignKey(blank=True, help_text="Contato individual alvo quando target_type=contact.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fiber_alarm_configs", to="setup_app.contact")),
                ("contact_group", models.ForeignKey(blank=True, help_text="Grupo de contatos alvo quando target_type=department_group.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fiber_alarm_configs", to="setup_app.contactgroup")),
                ("created_by", models.ForeignKey(blank=True, help_text="Usuário que criou a configuração.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fiber_alarm_configs_created", to=settings.AUTH_USER_MODEL)),
                ("fiber_cable", models.ForeignKey(help_text="Cabo de fibra ao qual esta configuração pertence.", on_delete=django.db.models.deletion.CASCADE, related_name="alarm_configs", to="inventory.fibercable")),
                ("system_user", models.ForeignKey(blank=True, help_text="Usuário do sistema alvo quando target_type=system_user.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fiber_alarm_configs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "inventory_fiber_alarm_config",
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="fibercablealarmconfig",
            index=models.Index(fields=["fiber_cable"], name="fiber_alarm_cable_idx"),
        ),
        migrations.AddIndex(
            model_name="fibercablealarmconfig",
            index=models.Index(fields=["target_type"], name="fiber_alarm_target_idx"),
        ),
    ]
