# Generated by Django 5.2.7 on 2026-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_fibercablealarmconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibercable',
            name='path_coordinates',
        ),
        migrations.RemoveField(
            model_name='routesegment',
            name='path_coordinates',
        ),
        migrations.AlterField(
            model_name='fibercablealarmconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
