# Generated by Django 5.2.7 on 2026-03-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_add_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercable',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Person or team responsible for this cable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='inventory.responsible'),
        ),
    ]
