# Generated by Django 5.2.7 on 2026-03-23 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_add_responsible_fk_to_fibercable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberCableAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_name', models.CharField(help_text='Nome do cabo no momento da ação (preservado mesmo após exclusão)', max_length=150)),
                ('username', models.CharField(blank=True, help_text='Login do usuário no momento da ação', max_length=150)),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluído')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of {field: {old: ..., new: ...}} for updated fields')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.fibercable')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_fibercable_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
