# Generated by Django 5.2.7 on 2026-03-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_add_fibercable_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order among siblings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.cablefolder')),
            ],
            options={
                'db_table': 'inventory_cable_folder',
                'ordering': ['order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fibercable',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Organising folder for this cable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='inventory.cablefolder'),
        ),
    ]
