# Generated by Django 5.2.7 on 2026-05-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_add_department_to_alarmconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberAlarmNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='break / attenuation / normalization (snapshot do alert_type da config)', max_length=16)),
                ('channel', models.CharField(help_text='whatsapp, email, sms, telegram', max_length=16)),
                ('recipient_label', models.CharField(blank=True, max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('recipient_email', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False, help_text="True quando a notificação veio do botão 'Enviar Teste' (sem evento real).")),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.fibercablealarmconfig')),
                ('event', models.ForeignKey(blank=True, help_text='Evento que disparou esta notificação (pode ser null em testes manuais).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.fiberevent')),
            ],
            options={
                'db_table': 'inventory_fiber_alarm_notification_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['config', 'event'], name='inventory_f_config__5d83fd_idx'), models.Index(fields=['-sent_at'], name='inventory_f_sent_at_4f55b3_idx')],
            },
        ),
    ]
