# Generated by Django 5.2.7 on 2026-05-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_fiberalarmnotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercablealarmconfig',
            name='snooze_until',
            field=models.DateTimeField(blank=True, help_text='Quando preenchido, suprime notificações automáticas até esse momento.', null=True),
        ),
    ]
