# Generated by Django 5.2.7 on 2025-10-19 18:33

import setup_app.fields
from django.db import migrations

FIELDS_TO_ENCRYPT = [
    'zabbix_api_key',
    'zabbix_user',
    'zabbix_password',
    'maps_api_key',
    'unique_licence',
]

def encrypt_existing(apps, schema_editor):
    FirstTimeSetup = apps.get_model('setup_app', 'FirstTimeSetup')
    for record in FirstTimeSetup.objects.all():
        updated_fields = []
        for field in FIELDS_TO_ENCRYPT:
            value = getattr(record, field)
            if value:
                setattr(record, field, value)
                updated_fields.append(field)
        if updated_fields:
            record.save(update_fields=updated_fields)

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimesetup',
            name='maps_api_key',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firsttimesetup',
            name='unique_licence',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firsttimesetup',
            name='zabbix_api_key',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firsttimesetup',
            name='zabbix_password',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firsttimesetup',
            name='zabbix_user',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.RunPython(encrypt_existing, noop),
    ]
