# Generated by Django 5.2.7 on 2026-01-06 10:55

import setup_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0005_configurationaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('server_type', models.CharField(choices=[('zabbix', 'Zabbix'), ('snmp', 'SNMP'), ('prometheus', 'Prometheus'), ('librenms', 'LibreNMS')], default='zabbix', max_length=20)),
                ('url', models.CharField(max_length=255)),
                ('auth_token', setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='map_provider',
            field=models.CharField(choices=[('google', 'Google Maps'), ('mapbox', 'Mapbox'), ('osm', 'OpenStreetMap')], default='google', max_length=20),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='mapbox_token',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
    ]
