# Generated by Django 5.2.7 on 2026-01-06 17:26

import setup_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0006_monitoringserver_firsttimesetup_map_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_host',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_password',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_path',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_port',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='ftp_user',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='gdrive_credentials_json',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=4096, max_plain_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='gdrive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='gdrive_folder_id',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
    ]
