# Generated by Django 5.2.7 on 2026-01-07 13:45

import setup_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0011_firsttimesetup_smtp_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_api_token',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_api_url',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=512, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_aws_access_key_id',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_aws_region',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=64, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_aws_secret_access_key',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_infobip_base_url',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_password',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_priority',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=16, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_provider',
            field=models.CharField(choices=[('smsnet', 'SMSNET'), ('zenvia', 'Zenvia'), ('totalvoice', 'TotalVoice'), ('aws_sns', 'AWS SNS'), ('infobip', 'Infobip')], default='smsnet', max_length=32),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_sender_id',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=64, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_test_message',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_test_recipient',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=64, max_plain_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_username',
            field=setup_app.fields.EncryptedCharField(blank=True, max_length=255, max_plain_length=255, null=True),
        ),
    ]
