# Generated by Django 5.2.7 on 2026-01-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0013_firsttimesetup_sms_provider_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gateway_type', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('smtp', 'SMTP')], max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
