# Generated by Django 5.2.7 on 2026-01-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_departments'),
        ('setup_app', '0017_videomosaic_alter_companyprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomosaic',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departamentos com permissão para visualizar este mosaico. Deixe vazio para acesso público (todos departamentos).', related_name='video_mosaics', to='core.department'),
        ),
    ]
