# Generated by Django 5.2.7 on 2026-01-27 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0021_add_site_to_videomosaic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Grupo de Contatos',
                'verbose_name_plural': 'Grupos de Contatos',
                'db_table': 'setup_contact_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('file_type', models.CharField(max_length=10, verbose_name='Tipo de arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total de linhas')),
                ('successful_imports', models.IntegerField(default=0, verbose_name='Importações bem-sucedidas')),
                ('failed_imports', models.IntegerField(default=0, verbose_name='Importações falhas')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='Lista de erros durante a importação', verbose_name='Log de erros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_imports', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Histórico de Importação',
                'verbose_name_plural': 'Histórico de Importações',
                'db_table': 'setup_contact_import_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Número deve estar no formato: '+5561999999999'. Até 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_message_sent', models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem enviada')),
                ('message_count', models.IntegerField(default=0, verbose_name='Total de mensagens enviadas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.ForeignKey(blank=True, help_text='Se preenchido, sincroniza com dados do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário vinculado')),
                ('groups', models.ManyToManyField(blank=True, related_name='contacts', to='setup_app.contactgroup', verbose_name='Grupos')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'setup_contacts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['phone'], name='setup_conta_phone_5ba027_idx'), models.Index(fields=['is_active'], name='setup_conta_is_acti_5df6aa_idx'), models.Index(fields=['created_at'], name='setup_conta_created_e66ca8_idx')],
            },
        ),
    ]
