# Generated by ChatGPT on 2026-02-01
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0024_add_map_theme_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                (
                    'category',
                    models.CharField(
                        choices=[('generic', 'Genérico'), ('optical_level', 'Nível óptico')],
                        default='generic',
                        max_length=40,
                    ),
                ),
                (
                    'channel',
                    models.CharField(
                        choices=[
                            ('sms', 'SMS'),
                            ('whatsapp', 'WhatsApp'),
                            ('telegram', 'Telegram'),
                            ('smtp', 'E-mail (SMTP)'),
                        ],
                        default='whatsapp',
                        max_length=16,
                    ),
                ),
                (
                    'subject',
                    models.CharField(
                        blank=True,
                        help_text='Usado apenas para envio por e-mail (SMTP).',
                        max_length=255,
                    ),
                ),
                (
                    'content',
                    models.TextField(help_text='Mensagem enviada ao contato. Use variáveis com {{chaves}}.'),
                ),
                (
                    'placeholders',
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de chaves utilizadas neste modelo.',
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name='created_alert_templates',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name='updated_alert_templates',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Modelo de aviso',
                'verbose_name_plural': 'Modelos de aviso',
                'ordering': ['name'],
                'db_table': 'setup_alert_templates',
                'indexes': [
                    models.Index(
                        fields=['category', 'channel'],
                        name='alert_tpl_cat_chan_idx',
                    )
                ],
            },
        ),
    ]
