# Generated by ChatGPT on 2026-02-01
from django.db import migrations, models


def drop_duplicate_defaults(apps, schema_editor):
    AlertTemplate = apps.get_model('setup_app', 'AlertTemplate')
    duplicates = (
        AlertTemplate.objects
        .filter(is_default=True)
        .order_by('category', 'channel', '-updated_at', '-id')
    )
    seen = set()
    for template in duplicates:
        key = (template.category, template.channel)
        if key in seen:
            template.is_default = False
            template.save(update_fields=['is_default'])
        else:
            seen.add(key)


def reverse_noop(apps, schema_editor):
    # No reverse operation needed; keeping defaults disabled is safe.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0025_alerttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='is_default',
            field=models.BooleanField(
                default=False,
                help_text='Quando verdadeiro, este modelo será usado como padrão para a categoria/canal.',
            ),
        ),
        migrations.RunPython(drop_duplicate_defaults, reverse_noop),
    ]
