# Generated by Django 5.2.7 on 2026-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0026_alerttemplate_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttemplate',
            name='category',
            field=models.CharField(choices=[('generic', 'Genérico'), ('optical_level', 'Nível óptico'), ('interface_signal', 'Sinal de interface'), ('device_availability', 'Disponibilidade de equipamento')], default='generic', max_length=40),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='firsttimesetup',
            name='map_type',
            field=models.CharField(default='terrain', max_length=20),
        ),
    ]
