# Generated by Django 5.2.7 on 2026-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0028_seed_cable_alert_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttemplate',
            name='category',
            field=models.CharField(choices=[('generic', 'Genérico'), ('optical_level', 'Nível óptico'), ('interface_signal', 'Sinal de interface'), ('device_availability', 'Disponibilidade de equipamento'), ('cable_break', 'Rompimento de cabo'), ('cable_attenuation', 'Atenuação de cabo'), ('cable_normalization', 'Normalização de serviço')], default='generic', max_length=40),
        ),
    ]
