# Generated by Django 5.2.7 on 2025-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='setup_app/logos/')),
                ('zabbix_url', models.CharField(max_length=255)),
                ('auth_type', models.CharField(choices=[('token', 'Token da API'), ('login', 'Usu?rio e Senha')], max_length=10)),
                ('zabbix_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('zabbix_user', models.CharField(blank=True, max_length=255, null=True)),
                ('zabbix_password', models.CharField(blank=True, max_length=255, null=True)),
                ('maps_api_key', models.CharField(max_length=255)),
                ('unique_licence', models.CharField(max_length=255)),
                ('configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
