# Generated by Django 5.2.7 on 2025-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0002_alter_firsttimesetup_maps_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimesetup',
            name='auth_type',
            field=models.CharField(choices=[('token', 'Zabbix API token'), ('login', 'Zabbix user and password')], max_length=10),
        ),
    ]
