# Generated by Django 5.2.7 on 2025-11-17 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0004_firsttimesetup_database_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('export', 'Exported'), ('import', 'Imported'), ('test', 'Connection Tested')], max_length=20)),
                ('section', models.CharField(help_text="Configuration section (e.g., 'Zabbix', 'Database', 'Redis')", max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (sanitized)')),
                ('new_value', models.TextField(blank=True, help_text='New value (sanitized)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='setup_app_c_timesta_b54e08_idx'), models.Index(fields=['section', '-timestamp'], name='setup_app_c_section_cbffe4_idx')],
            },
        ),
    ]
