# Generated by Django 5.2.7 on 2026-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0012_firsttimesetup_sms_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimesetup',
            name='sms_provider_rank',
            field=models.IntegerField(default=1),
        ),
    ]
