# Generated by Django 5.2.7 on 2026-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0016_remove_companyprofile_central_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMosaic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do mosaico', max_length=120)),
                ('layout', models.CharField(choices=[('2x2', '2×2 (4 câmeras)'), ('3x2', '3×2 (6 câmeras)'), ('3x3', '3×3 (9 câmeras)'), ('4x3', '4×3 (12 câmeras)'), ('4x4', '4×4 (16 câmeras)')], default='2x2', help_text='Layout da grade de vídeos', max_length=8)),
                ('cameras', models.JSONField(blank=True, default=list, help_text='Lista de IDs dos gateways de vídeo (MessagingGateway)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mosaico de Vídeo',
                'verbose_name_plural': 'Mosaicos de Vídeo',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messaginggateway',
            name='gateway_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('smtp', 'SMTP'), ('video', 'Videovigilância')], max_length=16),
        ),
    ]
