# Generated by Django 5.2.7 on 2026-01-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_departments'),
        ('setup_app', '0019_messaginggateway_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaginggateway',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departamentos com permissão para visualizar esta câmera. Deixe vazio para acesso público (todos departamentos).', related_name='video_cameras', to='core.department'),
        ),
    ]
