# Generated by Django 5.2.7 on 2026-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0023_add_map_configuration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttimesetup',
            name='map_theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='light', max_length=10),
        ),
    ]
