# Generated by Django 5.2.7 on 2026-10-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolucaoContador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ultimo_numero", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contador da Central",
            },
        ),
        migrations.CreateModel(
            name="EvolucaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=12, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("problema", "Problema"), ("ideia", "Ideia")], max_length=10
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("aceite", "Aceite"),
                            ("a_fazer", "A fazer"),
                            ("feito", "Feito"),
                            ("recusado", "Recusado"),
                        ],
                        db_index=True,
                        default="entrada",
                        max_length=10,
                    ),
                ),
                ("recusa_motivo", models.TextField(blank=True, default="")),
                ("recusado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "impacto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bloqueia", "Bloqueia"),
                            ("atrasa", "Atrasa"),
                            ("incomoda", "Incomoda"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("prioridade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("etiquetas", models.JSONField(blank=True, default=list)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                (
                    "origem",
                    models.CharField(
                        choices=[("humano", "Humano"), ("agente", "Agente")],
                        default="humano",
                        max_length=10,
                    ),
                ),
                ("evidencia", models.JSONField(blank=True, null=True)),
                ("fechado_por", models.JSONField(blank=True, null=True)),
                ("alerta_parado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolucao_itens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Central de Evolução",
                "verbose_name_plural": "Itens da Central de Evolução",
                "ordering": [models.OrderBy(models.F("prioridade"), nulls_last=True), "codigo"],
            },
        ),
        migrations.CreateModel(
            name="EvolucaoAnexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ficheiro", models.FileField(upload_to="evolucao/anexos/%Y/%m/")),
                ("nome_original", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=100)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "carregado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="evolucao.evolucaoitem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="evolucaoitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("prioridade__isnull", True),
                    models.Q(("prioridade__gte", 1), ("prioridade__lte", 4)),
                    _connector="OR",
                ),
                name="ck_evolucao_prioridade",
            ),
        ),
        migrations.AddConstraint(
            model_name="evolucaoitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "recusado"), _negated=True),
                    models.Q(("recusa_motivo", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_evolucao_recusa_com_motivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="evolucaoitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origem", "agente"), _negated=True),
                    ("evidencia__isnull", False),
                    _connector="OR",
                ),
                name="ck_evolucao_agente_com_prova",
            ),
        ),
    ]
